# Generated by Django 3.1.5 on 2021-01-27 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'ordering': ['categorie'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='background')),
            ],
        ),
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fruit', models.CharField(max_length=255, verbose_name="Nom de l'article")),
                ('information_fruit', models.TextField(verbose_name="detail du l'article")),
                ('prix_fruit', models.IntegerField(verbose_name="Prix de l'article")),
                ('quantite', models.IntegerField(default=1, verbose_name="Nombre d'article disponible")),
                ('poids', models.IntegerField(verbose_name="Poids de l'article")),
                ('nom_categorie', models.CharField(max_length=255, null=True)),
                ('prix', models.IntegerField(null=True, verbose_name='prix total')),
                ('Image', models.ImageField(upload_to='', verbose_name="Image de l'article")),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='produit.categorie', verbose_name="Categorie de l'article")),
            ],
        ),
    ]
